### ISSUE TITLE
Http: should return status code / text properly from errors

### ISSUE THREAD

**Issue by robwormald** [angular/http#54]
_From @robwormald on December 27, 2015 12:48_

Currently defaulting to the base, which is incorrect for network errors (CORS, etc)

_Copied from original issue: angular/angular#6138_

**Comment by gustavolira** [comment]
Any news about this?

**Comment by alvipeo** [comment]
I used fetch and XMLHttpRequest for now, as Rob told me. Works for now (where fetch is supported)

**Comment by gustavolira** [comment]
Can you give a example?

**Comment by alvipeo** [comment]
Here's the code (part of it) from my test:
```
// azure storage related headers
                const headers = {
                    'x-ms-blob-type': 'BlockBlob',
                    'Content-Length': blk.size.toString()
                };

                const reqOptions = {
                    method: "PUT",
                    headers: headers,
                    body: blk.body
                };

                if (!(window as any).fetch) {
                    throw Error("Fetch API is not supported");
                }

                const blkObs = Observable.of(blk);
                let fetchRes: Promise<Response> = fetch(putUri, reqOptions);
                const res = Observable.zip(blkObs, fetchRes);
                return res;
```

or 
```
        let xhr: XMLHttpRequest = new XMLHttpRequest();
        xhr.open("GET", "http://127.0.0.1:10000/devstoreaccount1/integration-tests/adidas_home_3.jpg");
        xhr.responseType = "arraybuffer";
        xhr.onload = (event: any) => {
            let blob: Blob = new Blob([xhr.response], { type: "image/jpeg" });

            expect(blob).toBeDefined();
            expect(blob.size).toBe(186935);

            const originalHash = hashes.MD5(JSON.stringify(xhr.response));
            const filename = "adidas_home_3.jpg";

            const file: File = new File([blob], filename, { type: "image/jpeg" });
            expect(file.size).toBe(blob.size);
...
```

**Comment by gustavolira** [comment]
My problem is that I'm using angular2-jwt, so I'm using their AuthHttp to make the requests with token and so on.... =(

**Comment by alvipeo** [comment]
Never used it. So no way of using fetch and XMLHttpRequest in there?

**Comment by gustavolira** [comment]
Hi,
Please, any news about this issue?

**Comment by vladimirgamalian** [comment]
May be someone knows a temporary hack/workaround?

**Comment by mgechev** [comment]
Using fetch you only need to add the `Authorization` header. Here's [an example](https://auth0.com/blog/2015/09/10/jwt-authentication-with-observables/).

**Comment by JustinPierce** [comment]
I noticed that Angular 2 seems to have hit the release candidate stage. Is this going to be fixed before release, or is everyone going to be rolling their own network access?

**Comment by yelhouti** [comment]
it seems like this was assigned to @jeffbcross in the file https://github.com/angular/http/blob/13553e7df0ee2617933de06392d644e0633ae8fe/src/XHRConnection.js line 43: //TODO (jeffbcross): analyse status and handle problems
could you fix it Jeff please before the beta is done, status codes are very important in many APIs, and used widely as you know.

**Comment by smitchell** [comment]
I still have this issue. In the console, I see this (I was testing error handling while our test environment was unwell).

> XMLHttpRequest cannot load https://mycompany.com/mobile-gateway/signin. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 400.

But what my code receives is this:

> {"_body":{"isTrusted":true},"status":200,"ok":true,"statusText":"Ok","headers":{},"type":3,"url":null}

The calling code looks like this:

```
return this.http.request(new Request(options))
                .map((res: Response) => <OauthResponse> res.json())
                .do((res: OauthResponse) => {
                    console.log('do: ' + JSON.stringify(res));
                    localStorage.setItem('access_token', res.access_token);
                    this.setStandardHeaders();
                })
                .catch(MobileGatewayService.handleSigninError);
```
Here you see how the logging above was done.

```
    private static handleSigninError(error: Response) {
        let response: any;
        try {
            console.log(JSON.stringify(error));
            // response = error.json();
            response = {
                status: 401,
                message: 'Sign-in Error.'
            };
            // If the body wasn't JSON, something else went wrong -
            // provide a normalized default error body.
        } catch ( jsonError ) {
            response = {
                status: 500,
                message: 'The system is unavailable at this time. Please try again later.'
            };
        }
        console.log('handleSigninError ' + response);
        return( Rx.Observable.throw( response ) );
    }
```

Is something that I'm doing, or not doing, causing Angular 2 to swallow the 400 error I see in the log?

**Comment by robertjd** [comment]
@smitchell has described the problem very accurately, and I'm seeing it as well.  It appears that http development has moved back to the main angular repo, so angular/angular#6138 seems to be the relevant one again.

**Comment by smitchell** [comment]
Changing the syntax of my call from this;

` .catch(this.handleSigninError);`

To this:

`.catch((res: Response) => this.handleSigninError(res));`

Seems to have fixed my problem. For the first time I've seen the actual error code returned to my error handler:

`handleSigninError {"_body":"{\"timestamp\":1465920358459,\"status\":500,\"error\":\"Internal Server Error\",\"exception\":\"com.netflix.zuul.exception.ZuulException\",\"message\":\"GENERAL\"}","status":500,"ok":false,"statusText":"Ok","headers":{"Content-Type":["application/json;charset=UTF-8"]},"type":2,"url":"https://test.ioubenefits.com/mobile-gateway/signin"}`

**Comment by awerlang** [comment]
this is due to dynamic vs lexical `this`. Another way:

```js
.catch(this.handleSigninError.bind(this));
```

**Comment by fdoddridge** [comment]
I am seeing this exact behavior, and the workaround @smitchell proposes above does not work.  I cannot seem to get access to the parent error with the "real" status codes.

I'm using: "@angular/http": "2.0.0-rc.1"

**Comment by awerlang** [comment]
@fdoddridge this repo is inactive, as per README. Moved to angular/angular. See the linked issues.

**Comment by saurabhvyas** [comment]
I am still getting this issue on rc3

**Comment by vicb** [comment]
> I am still getting this issue on rc3

- Please do not comment on closed issues,
- Create a new issue with a plunker. Thanks
