### ISSUE TITLE
Calls are not performed if the Observable doesn't have a subscribe method attached

### ISSUE THREAD

**Issue by sphaso** [angular/http#88]
By looking in the dev tools, I won't see this call:
```
this.http.get('http://google.com/');
```
But I will see this one:
```
this.http.get('http://google.com/').subscribe(z => {});
```

I've made a plnkr with an example: http://plnkr.co/edit/rQ5SQd

**Comment by laco0416** [comment]
That's correct. Http requests are always _cold_ streams. 

See: http://www.bennadel.com/blog/3035-http-requests-are-cold-lazy-streams-in-angular-2-beta-6.htm

**Comment by templth** [comment]
It's because observables are lazy. You need to subscribe to initialize them...

**Comment by sphaso** [comment]
Ah I see, thank you. 
That's the burden of ignorance. I'll close this.
