### ISSUE TITLE
feat(Response): implement Response.prototype.toString() to make for a nicer error message

### ISSUE THREAD

**Issue by jeffbcross** [angular/http#89]
If a `Response` is `onError`'d from http, and the application doesn't handle it, a vague exception will be raised, such as `Unhanded [Object object]`. We should implement a `toString` method on `Response` so that if the error isn't properly handled, a more useful description of the problem will display in the console.

See https://daveceddia.com/angular-2-errors/#exception-object-object for context.

CC @dceddia

**Comment by templth** [comment]
@jeffbcross I created the corresponding PR for this: https://github.com/angular/angular/pull/7511. I saw that the statusText isn't set on the response...

**Comment by dceddia** [comment]
Nice! This will take care of #7143 :) Should I close that one?
