### ISSUE TITLE
Problem making POST request to another port in localhost

### ISSUE THREAD

**Issue by Sandybhai** [angular/http#94]
I have tried making a POST request to a server running on another port in my localhost as follows --
$http({
    url: 'http://localhost:3002/signup',
    method: "POST",
    data: JSON.stringify({username:$scope.username, pass:$scope.pass}),
    headers: {'Content-Type': 'application/json'}
}).success(function (response) {
    console.log("sucesssful POST request")
}).error(function (response) {
    console.log("Error in request")
});

This results in OPTIONS packet instead of a POST one which is not the case when I make a request with the url as '/signup' . How do I handle this issue? I'm not very clear about CORS which comes up when I try checking out online. Thanks in advance.

**Comment by vicb** [comment]
That's CORS check Google
