### ISSUE TITLE
Use of '+' character in URLSearchParams()

### ISSUE THREAD

**Issue by gnujeremie** [angular/http#96]
Code exemple
```
let body = new URLSearchParams();

for (let i in values) {
    body.set(i, values[i]);
}

let options = RequestOptions();
options.headers.append('Content-Type', 'application/x-www-form-urlencoded')
return this.http.post(uri, body, options).then();
[...]
```

If ```values[i]``` has a '+' character in it, then it is replaced by spaces.

**Comment by laserus** [comment]
+1. 

This is a bug. I have a time in ISO8601 as param and it just removes + from +3:00

**Comment by laserus** [comment]
The correct place of the issue:
https://github.com/angular/angular/issues/11058
