### ISSUE TITLE
Problem with lowercase Access-Control-Request-Headers

### ISSUE THREAD

**Issue by WarGot-by** [angular/http#97]
Before I send POST request with custom header Authorization fires OPTIONS query. In OPTIONS responce I see Access-Control-Request-Headers : **authorization** with 400 error 

In POST request I send 

`Accept	application/json

Accept-Encoding	gzip, deflate, br

Accept-Language	en-US,en;q=0.5

**Authorization**	Bearer yJhbGciOiJSUzI1NiIsInR5cCI6IkpXUyJ9.eyJ1c2VybmFtZSI6Imdlb3JnLnBhdWxlbmthIiwiaWF0IjoiMTQ3NjY5NjEyOSJ9

Connection	keep-alive

Content-Length	49

Content-Type	application/x-www-form-urlencoded

Host	api.server02.com

Origin	http://localhost:4000

Referer	http://localhost:4000/

User-Agent	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 FirePHP/0.7.4
x-insight	activate`

In server apache config 
Header set "Access-Control-Allow-Headers": "Origin, X-Requested-With, Content-Type, Accept, **Authorization**"

May be some help me, how to fix this problem ? Use angular 1.5.0

**Comment by vicb** [comment]
Angular 1.x issues should be reported to angular/angular.js

@jeffbcross @robwormald could you please close this issue tracker ?
